export const mats = [
  {
    name: "Proof of Hero",
    startRange: "D5",
    endRange: "N9",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Evil Bone",
    startRange: "D10",
    endRange: "N14",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Dragon Fang",
    startRange: "D15",
    endRange: "N19",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Void Dust",
    startRange: "D20",
    endRange: "N24",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Fool's Chain",
    startRange: "D25",
    endRange: "N29",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Deadly Poisonous Needle",
    startRange: "D30",
    endRange: "N34",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Mystic Spinal Fluid",
    startRange: "D35",
    endRange: "N39",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Stake of Wailing Night",
    startRange: "D42",
    endRange: "N46",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Mystic Gunpowder",
    startRange: "D47",
    endRange: "N51",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Seed of Yggdrasil",
    startRange: "D52",
    endRange: "N56",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Ghost Lantern",
    startRange: "D57",
    endRange: "N61",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Octuplet Crystal",
    startRange: "D62",
    endRange: "N66",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Serpent Jewel",
    startRange: "D67",
    endRange: "N71",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Phoenix Feather",
    startRange: "D72",
    endRange: "N76",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Eternal Gear",
    startRange: "D79",
    endRange: "N83",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Forbidden Page",
    startRange: "D84",
    endRange: "N88",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Homunculus Baby",
    startRange: "D89",
    endRange: "N93",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Meteor Horseshoe",
    startRange: "D94",
    endRange: "N98",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Great Knight Medal",
    startRange: "D99",
    endRange: "N103",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Shell of Reminiscence",
    startRange: "D104",
    endRange: "N108",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Refined Magatama",
    startRange: "D109",
    endRange: "N113",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Eternal Ice",
    startRange: "D116",
    endRange: "N120",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Giant's Ring",
    startRange: "D121",
    endRange: "N125",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Aurora Steel",
    startRange: "D126",
    endRange: "N130",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Ancient Bell of Tranquility",
    startRange: "D131",
    endRange: "N135",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Arrowhead of Disastrous Sin",
    startRange: "D136",
    endRange: "N140",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Moonlit Tiara",
    startRange: "D141",
    endRange: "N145",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Divine Spirit Particle",
    startRange: "D146",
    endRange: "N150",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Claw of Chaos",
    startRange: "D153",
    endRange: "N157",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Heart of the Foreign God",
    startRange: "D158",
    endRange: "N162",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Dragon's Reverse Scale",
    startRange: "D163",
    endRange: "N167",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Spirit Root",
    startRange: "D168",
    endRange: "N172",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Warhorse's Young Horn",
    startRange: "D173",
    endRange: "N177",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Tearstone of Blood",
    startRange: "D178",
    endRange: "N182",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Black Beast Grease",
    startRange: "D183",
    endRange: "N187",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Lamp of Evil-Sealing",
    startRange: "D190",
    endRange: "N194",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Scarab of Wisdom",
    startRange: "D195",
    endRange: "N199",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Primordial Lanugo",
    startRange: "D200",
    endRange: "N204",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Cursed Beast Gallstone",
    startRange: "D205",
    endRange: "N209",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Egg of Truth",
    startRange: "T190",
    endRange: "AD194",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Glittering Star Shard",
    startRange: "T195",
    endRange: "AD199",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Saber",
    startRange: "T5",
    endRange: "AD9",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Archer",
    startRange: "T10",
    endRange: "AD14",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Lancer",
    startRange: "T15",
    endRange: "AD19",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Rider",
    startRange: "T20",
    endRange: "AD24",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Caster",
    startRange: "T25",
    endRange: "AD29",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Assassin",
    startRange: "T30",
    endRange: "AD34",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Secret Gem of Berserker",
    startRange: "T35",
    endRange: "AD39",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Magic Gem of Saber",
    startRange: "T42",
    endRange: "AD46",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Magic Gem of Archer",
    startRange: "T47",
    endRange: "AD51",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Magic Gem of Lancer",
    startRange: "T52",
    endRange: "AD56",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Magic Gem of Rider",
    startRange: "T57",
    endRange: "AD61",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Magic Gem of Caster",
    startRange: "T62",
    endRange: "AD66",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Magic Gem of Assassin",
    startRange: "T67",
    endRange: "AD71",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Magic Gem of Berserker",
    startRange: "T72",
    endRange: "AD76",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Gem of Saber",
    startRange: "T79",
    endRange: "AD83",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Gem of Archer",
    startRange: "T84",
    endRange: "AD88",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Gem of Lancer",
    startRange: "T89",
    endRange: "AD93",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Gem of Rider",
    startRange: "T94",
    endRange: "AD98",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Gem of Caster",
    startRange: "T99",
    endRange: "AD103",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Gem of Assassin",
    startRange: "T104",
    endRange: "AD108",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Gem of Berserker",
    startRange: "T109",
    endRange: "AD113",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Saber Monument",
    startRange: "T116",
    endRange: "AD120",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Archer Monument",
    startRange: "T121",
    endRange: "AD125",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Lancer Monument",
    startRange: "T126",
    endRange: "AD130",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Rider Monument",
    startRange: "T131",
    endRange: "AD135",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Caster Monument",
    startRange: "T136",
    endRange: "AD140",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Assassin Monument",
    startRange: "T141",
    endRange: "AD145",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Berserker Monument",
    startRange: "T146",
    endRange: "AD150",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Saber Piece",
    startRange: "T153",
    endRange: "AD157",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Archer Piece",
    startRange: "T158",
    endRange: "AD162",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Lancer Piece",
    startRange: "T163",
    endRange: "AD167",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Rider Piece",
    startRange: "T168",
    endRange: "AD172",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Caster Piece",
    startRange: "T173",
    endRange: "AD177",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Assassin Piece",
    startRange: "T178",
    endRange: "AD182",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Berserker Piece",
    startRange: "T183",
    endRange: "AD187",
    rarity: "silver",
    type: "mat",
  },
];
