export const mats = [
  {
    name: "Proof of Hero",
    startRange: "D5",
    endRange: "N9",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Evil Bone",
    startRange: "D10",
    endRange: "N14",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Dragon Fang",
    startRange: "D15",
    endRange: "N19",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Void Dust",
    startRange: "D20",
    endRange: "N24",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Fool's Chain",
    startRange: "D25",
    endRange: "N29",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Deadly Poisonous Needle",
    startRange: "D30",
    endRange: "N34",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Mystic Spinal Fluid",
    startRange: "D35",
    endRange: "N39",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Stake of Wailing Night",
    startRange: "D42",
    endRange: "N46",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Mystic Gunpowder",
    startRange: "D47",
    endRange: "N51",
    rarity: "bronze",
    type: "mat",
  },
  {
    name: "Seed of Yggdrasil",
    startRange: "D52",
    endRange: "N56",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Ghost Lantern",
    startRange: "D57",
    endRange: "N61",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Octuplet Crystal",
    startRange: "D62",
    endRange: "N66",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Serpent Jewel",
    startRange: "D67",
    endRange: "N71",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Phoenix Feather",
    startRange: "D72",
    endRange: "N76",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Eternal Gear",
    startRange: "D79",
    endRange: "N83",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Forbidden Page",
    startRange: "D84",
    endRange: "N88",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Homunculus Baby",
    startRange: "D89",
    endRange: "N93",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Meteor Horseshoe",
    startRange: "D94",
    endRange: "N98",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Great Knight Medal",
    startRange: "D99",
    endRange: "N103",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Shell of Reminiscence",
    startRange: "D104",
    endRange: "N108",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Refined Magatama",
    startRange: "D109",
    endRange: "N113",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Eternal Ice",
    startRange: "D116",
    endRange: "N120",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Giant's Ring",
    startRange: "D121",
    endRange: "N125",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Aurora Steel",
    startRange: "D126",
    endRange: "N130",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Ancient Bell of Tranquility",
    startRange: "D131",
    endRange: "N135",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Arrowhead of Disastrous Sin",
    startRange: "D136",
    endRange: "N140",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Moonlit Tiara",
    startRange: "D141",
    endRange: "N145",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Divine Spirit Particle",
    startRange: "D146",
    endRange: "N150",
    rarity: "silver",
    type: "mat",
  },
  {
    name: "Claw of Chaos",
    startRange: "D153",
    endRange: "N157",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Heart of the Foreign God",
    startRange: "D158",
    endRange: "N162",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Dragon's Reverse Scale",
    startRange: "D163",
    endRange: "N167",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Spirit Root",
    startRange: "D168",
    endRange: "N172",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Warhorse's Young Horn",
    startRange: "D173",
    endRange: "N177",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Tearstone of Blood",
    startRange: "D178",
    endRange: "N182",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Black Beast Grease",
    startRange: "D183",
    endRange: "N187",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Lamp of Evil-Sealing",
    startRange: "D190",
    endRange: "N194",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Scarab of Wisdom",
    startRange: "D195",
    endRange: "N199",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Primordial Lanugo",
    startRange: "D200",
    endRange: "N204",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Cursed Beast Gallstone",
    startRange: "D205",
    endRange: "N209",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Egg of Truth",
    startRange: "T190",
    endRange: "AD194",
    rarity: "gold",
    type: "mat",
  },
  {
    name: "Glittering Star Shard",
    startRange: "T195",
    endRange: "AD199",
    rarity: "gold",
    type: "mat",
  },
];
